SELECT * FROM DEPARTMENTS;
SELECT COUNT(*) FROM DEPARTMENTS;

SELECT * FROM LOCATIONS;
SELECT COUNT(*) FROM LOCATIONS;

--null values
SELECT COUNT(DEPARTMENT_ID)
FROM EMPLOYEES;


SELECT count(distinct distinct FIRST_NAME) FROM EMPLOYEES;

SELECT COUNT(*) FROM EMPLOYEES
WHERE JOB_ID IN('IT_PROG', 'SA_REP');

SELECT MAX(SALARY)
FROM EMPLOYEES;

SELECT MIN(SALARY)
FROM EMPLOYEES;

SELECT ROUND(AVG(SALARY), 2) -- rounds the number to 2 decimal places
FROM EMPLOYEES;

SELECT SUM(SALARY) FROM EMPLOYEES;