SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'B%';


SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'B____';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '__z__';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME like '%e';

SELECT * FROM EMPLOYEES
WHERE JOB_ID LIKE '%IT%';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'H%l'