SELECT * FROM EMPLOYEES;


SELECT * FROM EMPLOYEES
ORDER BY SALARY;


SELECT * FROM EMPLOYEES
ORDER BY SALARY ASC;


SELECT * FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID < 120
ORDER BY SALARY DESC;

SELECT * FROM EMPLOYEES
ORDER BY FIRST_NAME ASC, LAST_NAME DESC;