SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

SELECT FIRST_NAME FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, JOB_ID FROM EMPLOYEES;

SELECT * FROM LOCATIONS;

SELECT COUNTRY_NAME, COUNTRY_ID FROM COUNTRIES;
SELECT JOB_ID, JOB_TITLE FROM JOBS;