SELECT * FROM EMPLOYEES;


SELECT * FROM EMPLOYEES
WHERE FIRST_NAME = 'David';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME = 'David' AND LAST_NAME = 'Lee';

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE FIRST_NAME = 'Peter';

SELECT SALARY FROM EMPLOYEES
WHERE SALARY > 6000;

SELECT * FROM EMPLOYEES
ORDER BY FIRST_NAME ASC, LAST_NAME DESC;

SELECT EMAIL FROM EMPLOYEES
WHERE SALARY < 5000;

SELECT * FROM EMPLOYEES
WHERE SALARY > 7000 AND DEPARTMENT_ID = 60;

SELECT * FROM EMPLOYEES
WHERE SALARY >= 3000 And SALARY <= 9000;

SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 3000 AND 7000;

SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG' OR JOB_ID = 'MK-MAN';

--the following statement is a secondary soliution to display info for various different ids
SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID IN(121, 142, 154, 165, 187)

