SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES;

SELECT COUNT(*)
FROM EMPLOYEES
WHERE SALARY < 5000;

SELECT COUNT(*)
FROM EMPLOYEES
WHERE SALARY BETWEEN 6000 AND 7000;

SELECT DISTINCT REGION_ID
FROM COUNTRIES;

SELECT SALARY
FROM EMPLOYEES
WHERE LAST_NAME = 'Grant' AND FIRST_NAME = 'Douglas';

SELECT * FROM DEPARTMENTS
WHERE DEPARTMENT_NAME IN('IT', 'Public Relations', 'Sales', 'Executive');

SELECT MAX(SALARY) FROM EMPLOYEES;
SELECT MIN(SALARY) FROM EMPLOYEES;

SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT COUNT(*)
FROM DEPARTMENTS;

SELECT START_DATE
FROM JOB_HISTORY
ORDER BY START_DATE ASC;

SELECT START_DATE
FROM JOB_HISTORY
ORDER BY START_DATE DESC;

SELECT *
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%a%a%';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%';

SELECT *
FROM EMPLOYEES
WHERE JOB_ID LIKE '%IT%';

SELECT DISTINCT JOB_ID
FROM EMPLOYEES
WHERE JOB_ID LIKE '%CLERK';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A___';

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(50, 80, 100);

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID NOT IN(90, 60, 100, 130, 120);

SELECT JOB_ID
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT MAX(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT MIN(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT AVG(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
WHERE SALARY >= 5000
GROUP BY JOB_ID;

SELECT JOB_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, AVG(SALARY) as "average salary"
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING JOB_ID IN('IT_PROG', 'SA_REP','FI_ACCOUNT', 'AD_VP');

SELECT Max(SALARY), DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY) >30000 AND DEPARTMENT_ID !=50;








