SELECT * FROM COUNTRIES;



SELECT C.COUNTRY_NAME, R.REGION_NAME
FROM COUNTRIES C INNER JOIN REGIONS R
ON R.REGION_ID = C.REGION_ID;

SELECT * FROM JOBS;

SELECT E.FIRST_NAME, J.JOB_TITLE
FROM EMPLOYEES E JOIN JOBS J
    on E.JOB_ID = J.JOB_ID;

SELECT D.DEPARTMENT_NAME, L.CITY
FROM DEPARTMENTS D JOIN LOCATIONS L
    on D.LOCATION_ID = L.LOCATION_ID;

SELECT CITY, COUNTRY_NAME
FROM LOCATIONS JOIN COUNTRIES C
    on LOCATIONS.COUNTRY_ID = C.COUNTRY_ID;

SELECT FIRST_NAME, LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
on E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM LOCATIONS L INNER JOIN COUNTRIES C
on L.COUNTRY_ID = C.COUNTRY_ID
INNER JOIN REGIONS R
on C.REGION_ID = R.REGION_ID;


SELECT E.FIRST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E INNER JOIN JOBS J
on E.JOB_ID = J.JOB_ID
INNER JOIN DEPARTMENTS D
on E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
on D.LOCATION_ID = L.LOCATION_ID;

SELECT E.FIRST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME, L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM EMPLOYEES E INNER JOIN JOBS J
on E.JOB_ID = J.JOB_ID
INNER JOIN DEPARTMENTS D
on E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
on D.LOCATION_ID = L.LOCATION_ID
INNER JOIN COUNTRIES C
on L.COUNTRY_ID = C.COUNTRY_ID
INNER JOIN REGIONS R
on C.REGION_ID = R.REGION_ID;


SELECT E.FIRST_NAME, E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM DEPARTMENTS D LEFT OUTER JOIN EMPLOYEES E
on D.DEPARTMENT_ID = E.DEPARTMENT_ID;

SELECT DEPARTMENT_NAME, L.LOCATION_ID, COUNTRY_ID
FROM LOCATIONS L LEFT OUTER JOIN DEPARTMENTS D
    on L.LOCATION_ID = D.LOCATION_ID
ORDER BY 1; 
