SELECT *
FROM LOCATIONS;

SELECT STREET_ADDRESS || ', ' || city || ' ' || POSTAL_CODE || ', ' || COUNTRY_ID
           as "Full Address"
FROM LOCATIONS;

SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);


SELECT min(SALARY)
FROM EMPLOYEES
WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES);

SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY)
                FROM EMPLOYEES
                WHERE SALARY > (SELECT MIN(SALARY)
                                FROM EMPLOYEES));


--6461 is avg

SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT *
FROM EMPLOYEES
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID in (select MANAGER_ID
                      from EMPLOYEES
                      WHERE FIRST_NAME = 'Neena');

SELECT MIN(SALARY)
FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM < 4;


SELECT MIN(SALARY)
FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM < 6;

SELECT MIN(SALARY)
FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM < 8;

SELECT MIN(SALARY)
FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM < 11;

SELECT MAX(SALARY)
FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY ASC)
WHERE ROWNUM < 4;

SELECT MAX(SALARY)
FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY ASC)
WHERE ROWNUM < 6;