SELECT * FROM EMPLOYEES;


--1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND REGION TABLE
SELECT C.COUNTRY_NAME, R.REGION_NAME
FROM COUNTRIES C
INNER JOIN REGIONS R on C.REGION_ID = R.REGION_ID;

--2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE

SELECT E.FIRST_NAME, J.JOB_TITLE
FROM EMPLOYEES E
INNER JOIN JOBS J ON E.JOB_ID = J.JOB_ID;

--3. FIND OUT DEPARTMENT_NAME AND CITY

SELECT DEPARTMENT_NAME, CITY
FROM LOCATIONS L
INNER JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID;

--4. FIND OUT ALL CITIES AND COUNTRY NAMES

SELECT CITY, COUNTRY_NAME
FROM LOCATIONS L
INNER JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID;

--5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME FOR DEPARTMENT ID 80 OR 40

SELECT E.FIRST_NAME, E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IN(80, 40);

--6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY

SELECT L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM LOCATIONS L
INNER JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
INNER JOIN REGIONS R on C.REGION_ID = R.REGION_ID;

--7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY

SELECT FIRST_NAME, JOB_TITLE, DEPARTMENT_NAME, CITY
FROM EMPLOYEES E
INNER JOIN JOBS J ON E.JOB_ID = J.JOB_ID
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;

--8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY , COUNTRY_NAME , REGION_NAME

SELECT FIRST_NAME, JOB_TITLE, DEPARTMENT_NAME, CITY, COUNTRY_NAME, REGION_NAME
FROM EMPLOYEES E
INNER JOIN JOBS J ON E.JOB_ID = J.JOB_ID
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
INNER JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
INNER JOIN REGIONS R ON C.REGION_ID = R.REGION_ID;

--9. FIND OUT EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL DEPARTMENTS INCLUDING WHERE DO NOT HAVE ANY EMPLOYEE.

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS D
LEFT OUTER JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

--10. FIND OUT ALL DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_ID INCLUDING THOSE LOCATIONS WITH NO DEPARTMENT

SELECT DEPARTMENT_NAME, LOCATION_ID, COUNTRY_ID
FROM LOCATIONS L
LEFT OUTER JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID;

--OR

SELECT DEPARTMENT_NAME, LOCATION_ID, COUNTRY_ID
FROM DEPARTMENTS D
RIGHT OUTER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
ORDER BY 1;


--11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT

SELECT DEPARTMENT_NAME, LOCATION_ID, COUNTRY_NAME
FROM DEPARTMENTS D
RIGHT OUTER JOIN LOCATIONS L on L.LOCATION_ID = D.LOCATION_ID
RIGHT OUTER JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID;


--12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT NAME INCLUDING THOSE DOES NOT HAVE DEPARTMENT, INCLUDING THOSE DEPARTMENTS DOES NOT HAVE ANY MATCHING EMPLOYEES