SELECT * FROM CUSTOMER;
SELECT * FROM ADDRESS;

SELECT FIRST_NAME, LAST_NAME, ADDRESS, PHONE
FROM CUSTOMER JOIN ADDRESS
ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

--What if we want to see customer table address_id information too
SELECT FIRST_NAME, LAST_NAME, ADDRESS, CUSTOMER.ADDRESS_ID, PHONE
FROM CUSTOMER JOIN ADDRESS
ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

--ADding table aliases
--all this does is shorten the code
--INNER JOIN
SELECT FIRST_NAME, LAST_NAME, ADDRESS, C.ADDRESS_ID,A.ADDRESS_ID , PHONE
FROM CUSTOMER C INNER JOIN ADDRESS A
 ON C.ADDRESS_ID = A.ADDRESS_ID;


--left join
SELECT FIRST_NAME, LAST_NAME, ADDRESS, C.ADDRESS_ID,A.ADDRESS_ID , PHONE
FROM CUSTOMER C LEFT JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID;

--right join
SELECT FIRST_NAME, LAST_NAME, ADDRESS, C.ADDRESS_ID,A.ADDRESS_ID , PHONE
FROM CUSTOMER C RIGHT JOIN ADDRESS A
 ON C.ADDRESS_ID = A.ADDRESS_ID;

SELECT FIRST_NAME, LAST_NAME, ADDRESS, C.ADDRESS_ID,A.ADDRESS_ID , PHONE
FROM CUSTOMER C FULL JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID;
